version: 2.1
# Executor digunakan untuk menentukan Image yang akan menjalankan steps yang kita tentukan pada jobs
executors:
  docker:
    docker:
      - image: cimg/base:2022.11-22.04
  golang:
    docker:
      - image: golang:latest

#Jobs adalah task yang akan dikerjakan untuk melakukan CI
jobs:
#Job pertama Lint berfungsi untuk menginstal hadolint dan menjalankannya terhadap berkas Dockerfile.
  lint:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
#Job kedua build_app_karsajobs_ui menjalankan beberapa fungsi untuk build dan push ke github repository
  build_app_karsajobs_ui:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
#Pada step ini berguna untuk build docker yang ada pada file menjadi docker image
      - run:
          name: Docker Build
          command: docker build -t karsajobs-ui:latest .
#Pada step ini memberikan tag pada docker yang sudah kita build menjadi image 
      - run:
          name: Add Docker Tag
          command: docker tag karsajobs-ui:latest ghcr.io/maliqpotter09/karsajobs-ui:latest
#Pada step ini melakukan login ke github repository
      - run:
          name: Docker Login
          command: echo $PASSWORD_DOCKER_HUB | docker login ghcr.io --username $USERNAME_DOCKER_HUB --password-stdin
#Pada step ini melakukan push docker image ke github repository kita
      - run:
          name: Docker Push
          command: docker push ghcr.io/maliqpotter09/karsajobs-ui:latest

#Workflo berfungsi untuk menjalankan job yang sudah kita buat
workflows:
  version: 2
  karsajobs_ui:
    jobs:
      - lint
#Menggunakan require, artinya job ini dapat dijalankan jika job yang ditentukan sudah selesai berjalan
#Menambahkan context, berfungsi juga sebagai environment variable yang sudah kita buat di CircleCI
      - build_app_karsajobs_ui:
          context: PASSWORD_DOCKER_HUB
          requires:
            - lint